server:
  port: 80
  servlet:
    # 项目虚拟路径
    context-path: /
spring:
  application:
    name: base
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.base.org:3306/db_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:738e7101490b}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:5}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  security:
    user:
      name: admin
      password: Admin@123
  redis:
    database: 0
    host: redis.base.org
    port: 6379
    password: ^#@^$(@&&@awdsccdawpq028372
    timeout: 20000        # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 20000     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    # 配置静态资源位置（不配置无法打开）
    static-locations: classpath:/static/,classpath:/templates/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    username: 3304604817@qq.com
    password: zyzxisbfoyrbdajg
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  # 指定写xml文件位置
  mapper-locations:
    classpath:mapper/**/*.xml
# 启用SQL日志打印
logging:
  level:
    com.base.basic.infra.mapper.AuditLogMapper: error
    com.base.basic.infra.mapper: debug
rocketmq:
  name-server: rocketmq.base.org:9876
  producer:
    group: basic-group
  consumer:
    group: basic-group
ribbon:
  eager-load:
    # 开启饿加载
    enabled: true
    # 饿加载服务
    clients: basic
minio:
  url: http://minio.base.org:9100
  access-key: gaoyang
  secret-key: gaoyang@123
  bucket-name: private
