server:
  port: 80
  servlet:
    # 项目虚拟路径
    context-path: /
spring:
  application:
    name: base
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.base.org:3306/db_base?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root@123456}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:5}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  security:
    user:
      name: admin
      password: Admin@123
  redis:
    database: 0
    host: ${SPRING_REDIS_HOST:redis.base.org}
    port: 6379
    password: '%^#&@%#*$(62748tegb'
    timeout: 20000        # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 20000     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    # 配置静态资源位置（不配置无法打开）
    static-locations: classpath:/static/,classpath:/templates/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    username: ${SPRING_MAIL_URL:xxx@qq.com}
    password: zyzxisbfoyrbdajg
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  # 指定写xml文件位置,classpath* 是扫描所有包括jar中的class
  mapper-locations:
    classpath*:/mapper/**/*.xml
# 启用SQL日志打印
logging:
  level:
    com.base.basic.infra.mapper.AuditLogMapper: error
    com.base.basic.infra.mapper.DbCacheMapper: error
    com.base.basic.infra.mapper.ScheduledMapper: error
    com.base.basic.infra.mapper: debug
ribbon:
  eager-load:
    # 开启饿加载
    enabled: true
    # 饿加载服务
    clients: basic
minio:
  url: ${SPRING_MINIO_URL:http://minio.base.org:9100}
  access-key: gaoyang
  secret-key: gaoyang@123
  bucket-name: private
translate:
  # 百度翻译API认证
  baidu:
    url: ${SPRING_TRANSLATE_BAIDU_URL:https://fanyi-api.baidu.com/api/trans/vip/translate}
    app-id: ${SPRING_TRANSLATE_BAIDU_APP_ID:20221120001462114}
    secret-key: ${SPRING_TRANSLATE_BAIDU_SECRET_KEY:87ghy8VKMd0cOOVUQto4}
